---
# tasks file for cornerstone

#
# =============================================================================
# Common Tasks
# =============================================================================
#
- include: common-{{ cornerstone_platform }}.yml
  tags: [common, "{{ cornerstone_platform }}"]
  when:
    - cornerstone_platform != 'libvirt'

#
# =============================================================================
# Network Tasks
# =============================================================================
#
- include: network-{{ cornerstone_platform }}.yml
  tags: [network, "{{ cornerstone_platform }}"]
  when:
    - cornerstone_platform != 'libvirt'

#
# =============================================================================
# Virtual Machine Tasks
# feature/adding_vmware_capabilities
# =============================================================================

#  include: "vm-{{ item.value.cornerstone_platform }}.yml"

  # ============================== #
  #   CURRENT SUPPORT PLATFORMS:   #
  #  AWS, AZURE, LIBVIRT & VMWARE  #
  # ============================== #

- name: Build vms based on dict
  #include_tasks: "vm-{{ item.value.cornerstone_platform }}.yml"
  include_tasks: "vm-{{ item.value.cornerstone_platform }}.yml"
  vars:
    cornerstone_tag_purpose: "{{ item.value.cornerstone_tag_purpose }}"
    cornerstone_tag_role: "{{ item.value.cornerstone_tag_role }}"
    cornerstone_vm_name: "{{ item.value.cornerstone_vm_name }}"
    cornerstone_vm_state: "{{ item.value.cornerstone_vm_state }}"
    cornerstone_location: "{{ item.value.cornerstone_location }}"
    cornerstone_vm_aws_az: "{{ item.value.cornerstone_vm_aws_az }}"
    cornerstone_vm_flavour: "{{ item.value.cornerstone_vm_flavour }}"
    cornerstone_vm_aws_ami: "{{ item.value.cornerstone_vm_aws_ami }}"
    cornerstone_vm_aws_sg: "{{ item.value.cornerstone_vm_aws_sg }}"
    cornerstone_virtual_network_name: "{{ item.value.cornerstone_virtual_network_name }}"
    cornerstone_virtual_network_cidr: "{{ item.value.cornerstone_virtual_network_cidr }}"
    cornerstone_vm_private_ip: "{{ item.value.cornerstone_vm_private_ip }}"
    cornerstone_subnet_name: "{{ item.value.cornerstone_subnet_name }}"
    cornerstone_vm_assign_public_ip: "{{ item.value.cornerstone_vm_assign_public_ip }}"
    cornerstone_vm_public_ip: "{{ item.value.cornerstone_vm_public_ip }}"
    cornerstone_public_private_ip: "{{ item.value.cornerstone_public_private_ip }}"
    cornerstone_publicip_allocation_method: "{{ item.value.cornerstone_publicip_allocation_method }}"
    cornerstone_publicip_domain_name: "{{ item.value.cornerstone_publicip_domain_name }}"
    cornerstone_public_private_domain_name: "{{ item.value.cornerstone_public_private_domain_name }}"
    cornerstone_vm_os_disk_size: "{{ item.value.cornerstone_vm_os_disk_size }}"
    cornerstone_vm_data_disk: "{{ item.value.cornerstone_vm_data_disk }}"
    cornerstone_vm_data_disk_device_name: "{{ item.value.cornerstone_vm_data_disk_device_name }}"
    cornerstone_aws_vm_data_disk_managed: "{{ item.value.cornerstone_aws_vm_data_disk_managed }}"
    cornerstone_azure_vm_disk_managed: "{{ item.value.cornerstone_azure_vm_disk_managed }}"
    cornerstone_vm_data_disk_size: "{{ item.value.cornerstone_vm_data_disk_size }}"
    cornerstone_vm_location: "{{ item.value.cornerstone_vm_location }}"
    cornerstone_working_dir: "{{ item.value.cornerstone_working_dir }}"
    cornerstone_vm_libvirt_template: "{{ item.value.cornerstone_vm_libvirt_template }}"
    cornerstone_vm_libvirt_file_type: "{{ item.value.cornerstone_vm_libvirt_file_type }}"
    cornerstone_vm_libvirt_vmtype: "{{ item.value.cornerstone_vm_libvirt_vmtype }}"
    cornerstone_vm_libvirt_vmos: "{{ item.value.cornerstone_vm_libvirt_vmos }}"
    cornerstone_vm_libvirt_vmmem: "{{ item.value.cornerstone_vm_libvirt_vmmem }}"
    cornerstone_vm_libvirt_vmcores: "{{ item.value.cornerstone_vm_libvirt_vmcores }}"
    cornerstone_vm_subnet: "{{ item.value.cornerstone_vm_subnet }}" 
    cornerstone_vm_gateway: "{{ item.value.cornerstone_vm_gateway }}"
    cornerstone_vm_dns1: "{{ item.value.cornerstone_vm_dns1 }}"
    cornerstone_vm_dns2: "{{ item.value.cornerstone_vm_dns2 }}"
    cornerstone_vm_ip: "{{ item.value.cornerstone_vm_ip }}"
    cornerstone_vm_extra_nics: "{{item.value.cornerstone_vm_extra_nics}}"
    cornerstone_vm_netname: "{{item.value.cornerstone_vm_netname}}"
    cornerstone_storage_type: "{{item.value.cornerstone_storage_type}}"
  # ========================================================================== #
  # BELOW ARE THE AZURE RELATED ITEMS
  # ========================================================================== #
    cornerstone_vm_image_offer: "{{item.value.cornerstone_vm_image_offer}}"
    cornerstone_vm_image_publisher: "{{item.value.cornerstone_vm_image_publisher}}"
    cornerstone_vm_image_sku: "{{item.value.cornerstone_vm_image_sku}}"
    cornerstone_vm_image_version: "{{item.value.cornerstone_vm_image_version}}"
    cornerstone_vm_azure_image: "{{item.value.cornerstone_vm_azure_image}}"
  # ========================================================================== #
  #  BELOW IS THE VMWARE HOST DEFINITION ITEMS USED FOR MAKING A VMWARE GUEST  #
  #    SOME DEFINITIONS FROM ABOVE ARE ALSO USED LIKE PLATFORM, STATE, ETC
  # ========================================================================== #
    cornerstone_vmware_hostname: "{{ item.value.cornerstone_vmware_hostname }}"
    cornerstone_vmware_username: "{{ item.value.cornerstone_vmware_username }}"
    cornerstone_vmware_password: "{{ item.value.cornerstone_vmware_password }}"
    cornerstone_vmware_destination: "{{ item.value.cornerstone_vmware_destination }}"
    cornerstone_vmware_template: "{{ item.value.cornerstone_vmware_template }}"
    cornerstone_vmware_disk_size: "{{ item.value.cornerstone_vm_os_disk_size }}"
    cornerstone_vmware_disk_type: "{{ item.value.cornerstone_vmware_disk_type }}"
    cornerstone_vmware_datastore: "{{ item.value.cornerstone_vmware_datastore }}"
    cornerstone_vmware_memory: "{{ item.value.cornerstone_vmware_memory }}"
    cornerstone_vmware_cpu_count: "{{ item.value.cornerstone_vmware_cpu_count }}"
    cornerstone_vmware_socket_cores: "{{ item.value.cornerstone_vmware_socket_cores }}"
    cornerstone_vmware_scsi_type: "{{ item.value.cornerstone_vmware_scsi_type }}"
    cornerstone_vmware_memory_lock: "{{ item.value.cornerstone_vmware_memory_lock }}"
    cornerstone_vmware_memory_limit: "{{ item.value.cornerstone_vmware_memory_limit }}"
    cornerstone_vmware_memory_reservation: "{{ item.value.cornerstone_vmware_memory_reservation }}"
    cornerstone_vmware_cpu_limit: "{{ item.value.cornerstone_vmware_cpu_limit }}"
    cornerstone_vmware_cpu_reservation: "{{ item.value.cornerstone_vmware_cpu_reservation }}"
    cornerstone_vmware_max_connection: "{{ item.value.cornerstone_vmware_max_connection }}"
    cornerstone_vmware_hotadd_cpu: "{{ item.value.cornerstone_vmware_hotadd_cpu }}"
    cornerstone_vmware_hotremove_cpu: "{{ item.value.cornerstone_vmware_hotremove_cpu }}"
    cornerstone_vmware_hotadd_memory: "{{ item.value.cornerstone_vmware_hotadd_memory }}"
    cornerstone_vmware_hardware_version: "{{ item.value.cornerstone_vmware_hardware_version }}"
    cornerstone_vmware_iso_datastore: "{{ item.value.cornerstone_vmware_iso_datastore }}"
    cornerstone_vmware_iso_name: "{{ item.value.cornerstone_vmware_iso_name }}"
    cornerstone_vmware_network_name: "{{ item.value.cornerstone_vmware_network_name }}"
    cornerstone_vmware_nic_mac: "{{ item.value.cornerstone_vmware_nic_mac }}"
    # ========================================================================== #
    # BELOW ARE THE GCP RELATED ITEMS
    # ========================================================================== #
    cornerstone_gcp_project: "{{ item.value.cornerstone_gcp_project }}"
    cornerstone_gcp_auth_kind: "{{ item.value.cornerstone_gcp_auth_kind }}"
    cornerstone_service_account_file: "{{ item.value.cornerstone_service_account_file }}"
    cornerstone_gcp_zone: "{{ item.value.cornerstone_gcp_zone }}"
    cornerstone_vm_gcp_source_image: "{{ item.value.cornerstone_vm_gcp_source_image }}"
  loop: "{{ guests|dict2items }}"  
  tags: [vm, "{{ cornerstone_platform }}"]

# =============================================================================
# Discover IP Address Tasks
# =============================================================================

- name: Discover IP address tasks
  include: discover-ip-{{ cornerstone_platform }}.yml
  vars:
    cornerstone_platform: "{{ item.value.cornerstone_platform }}"
    cornerstone_tag_purpose: "{{ item.value.cornerstone_tag_purpose }}"
    cornerstone_tag_role: "{{ item.value.cornerstone_tag_role }}"
    cornerstone_vm_name: "{{ item.value.cornerstone_vm_name }}"
    cornerstone_vm_state: "{{ item.value.cornerstone_vm_state }}"
    cornerstone_location: "{{ item.value.cornerstone_location }}"
    cornerstone_vm_aws_az: "{{ item.value.cornerstone_vm_aws_az }}"
    cornerstone_vm_flavour: "{{ item.value.cornerstone_vm_flavour }}"
    cornerstone_vm_aws_ami: "{{ item.value.cornerstone_vm_aws_ami }}"
    cornerstone_vm_aws_sg: "{{ item.value.cornerstone_vm_aws_sg }}"
    cornerstone_virtual_network_name: "{{ item.value.cornerstone_virtual_network_name }}"
    cornerstone_virtual_network_cidr: "{{ item.value.cornerstone_virtual_network_cidr }}"
    cornerstone_subnet_name: "{{ item.value.cornerstone_subnet_name }}"
    cornerstone_vm_assign_public_ip: "{{ item.value.cornerstone_vm_assign_public_ip }}"
    cornerstone_vm_public_ip: "{{ item.value.cornerstone_vm_public_ip }}"
    cornerstone_public_private_ip: "{{ item.value.cornerstone_public_private_ip }}"
    cornerstone_publicip_allocation_method: "{{ item.value.cornerstone_publicip_allocation_method }}"
    cornerstone_publicip_domain_name: "{{ item.value.cornerstone_publicip_domain_name }}"
    cornerstone_vm_data_disk: "{{ item.value.cornerstone_vm_data_disk }}"
    cornerstone_vm_data_disk_device_name: "{{ item.value.cornerstone_vm_data_disk_device_name }}"
    cornerstone_aws_vm_data_disk_managed: "{{ item.value.cornerstone_aws_vm_data_disk_managed }}"
    cornerstone_vm_data_disk_size: "{{ item.value.cornerstone_vm_data_disk_size }}"
    cornerstone_vm_location: "{{ item.value.cornerstone_vm_location }}"
    cornerstone_working_dir: "{{ item.value.cornerstone_working_dir }}"
    cornerstone_vm_libvirt_template: "{{ item.value.cornerstone_vm_libvirt_template }}"
    cornerstone_vm_libvirt_file_type: "{{ item.value.cornerstone_vm_libvirt_file_type }}"
    cornerstone_vm_libvirt_vmtype: "{{ item.value.cornerstone_vm_libvirt_vmtype }}"
    cornerstone_vm_libvirt_vmos: "{{ item.value.cornerstone_vm_libvirt_vmos }}"
    cornerstone_vm_libvirt_vmmem: "{{ item.value.cornerstone_vm_libvirt_vmmem }}"
    cornerstone_vm_libvirt_vmcores: "{{ item.value.cornerstone_vm_libvirt_vmcores }}"
    cornerstone_vm_subnet: "{{ item.value.cornerstone_vm_subnet }}"
    cornerstone_vm_gateway: "{{ item.value.cornerstone_vm_gateway }}"
    cornerstone_vm_dns1: "{{ item.value.cornerstone_vm_dns1 }}"
    cornerstone_vm_dns2: "{{ item.value.cornerstone_vm_dns2 }}"
    cornerstone_vm_ip: "{{ item.value.cornerstone_vm_ip }}"
    #    cornerstone_ssh_extra_args: "{{item.value.cornerstone_ssh_extra_args}}"
    cornerstone_python_interpreter: "{{item.value.cornerstone_python_interpreter}}"
    #    cornerstone_ssh_vars: "{{ item.value.cornerstone_ssh_vars }}"
  loop: "{{ guests|dict2items }}"
  tags: ["{{ cornerstone_platform }}"]

  #cornerstone_ssh_vars:
  #      - { varname: "{{ item[1].varname }}", varvalue: "{{ item[1].varvalue }}" }
  #  with_subelements:
  #  - "{{ guests }}"
  #  - cornerstone_ssh_vars


# EOF
