---

- name: "Create VMWare Guest {{ cornerstone_vmware_hostname }}"
  vmware_guest:
    hostname: "{{ cornerstone_vmware_hostname }}"
    username: "{{ cornerstone_vmware_username }}"
    password: "{{ cornerstone_vmware_password }}"
    validate_certs: no
    folder: "{{ cornerstone_vmware_destination }}"
    name: "{{ cornerstone_vm_name }}"
    state: "{{ cornerstone_vm_state }}"
    template: "{{ cornerstone_vmware_template }}"
    disk:
    - size_gb: "{{ cornerstone_vmware_disk_size }}"
      type: "{{ cornerstone_vmware_disk_type }}"
      datastore: "{{ cornerstone_vmware_datastore }}"
    hardware:
      memory_mb: "{{ cornerstone_vmware_memory }}"
      num_cpus: "{{ cornerstone_vmware_cpu_count }}"
      num_cpu_cores_per_socket: "{{ cornerstone_vmware_socket_cores }}"
      scsi: "{{ cornerstone_vmware_scsi_type }}"
      memory_reservation_lock: "{{ cornerstone_vmware_memory_lock }}"
      mem_limit: "{{ cornerstone_vmware_memory_limit }}"
      mem_reservation: "{{ cornerstone_vmware_memory_reservation }}"
      cpu_limit: "{{ cornerstone_vmware_cpu_limit }}"
      cpu_reservation: "{{ cornerstone_vmware_cpu_reservation }}"
      max_connections: "{{ cornerstone_vmware_max_connection }}"
      hotadd_cpu: "{{ cornerstone_vmware_hotadd_cpu }}"
      hotremove_cpu: "{{ cornerstone_vmware_hotremove_cpu }}"
      hotadd_memory: "{{ cornerstone_vmware_hotadd_memory }}"
      version: "{{ cornerstone_vmware_hardware_version }}" # Hardware version of virtual machine
      boot_firmware: "efi"
    cdrom:
      type: iso
      iso_path: "{{ cornerstone_vmware_iso_datastore}} {{ cornerstone_vmware_iso_name }}"
    networks:
    - name: "{{ cornerstone_vmware_network_name }}"
      mac: "{{ cornerstone_vmware_nic_mac }}"
    wait_for_ip_address: 'true'
  when: "{{ cornerstone_vmware_use_template }}" is true